version: '2'
services:
  nginx:
    build:
      context: .
      dockerfile: nginxDockerfile
    ports:
      - 80:80
      - 443:80
    links:
      - php-fpm
    volumes:
      - project:/usr/share/nginx/app
  php-fpm:
    depends_on:
      - database
    build:
      context: .
      dockerfile: php-fpmDockerfile
    links:
      - database
    volumes:
      - project:/usr/share/nginx/app
    environment:
      - DB_HOST=database
  database:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
volumes:
  project:
